FROM python:3.11-slim

WORKDIR /app

# Copier les dépendances LÉGÈRES (pas requirements.txt complet)
COPY docker/requirements-api.txt .
RUN pip install --no-cache-dir -r requirements-api.txt

# Copier le projet
COPY src/ ./src/
COPY configs/ ./configs/
COPY models/ ./models/

# Variables d'environnement
ENV PYTHONPATH=/app
ENV MODEL_PATH=/app/models/model.pkl

EXPOSE 8000

CMD ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000"]