FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ ./src/
COPY configs/ ./configs/
COPY data/ ./data/

# Entraîner le modèle au build (optionnel) ou au run
CMD ["python", "src/models/train.py"]