FROM apache/airflow:2.10.3-python3.12

# Dépendances nécessaires pour le pipeline MLOps
# (sans tensorflow/prophet qui sont trop lourds pour Airflow)
RUN pip install --no-cache-dir \
    mlflow==2.10.0 \
    pandas==2.1.4 \
    numpy==1.26.3 \
    scikit-learn==1.4.0 \
    xgboost==2.0.3 \
    "pyarrow>=15.0.0" \
    pyyaml==6.0.1 \
    python-dotenv==1.0.0 \
    "pydantic>=2.0.0" \
    requests==2.31.0