x-airflow-common: &airflow-common
  build:
    context: ..
    dockerfile: docker/Dockerfile.airflow
  environment:
    - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
    - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
    - PYTHONPATH=/opt/airflow/project
  volumes:
    - ../airflow:/opt/airflow
    - ..:/opt/airflow/project

services:
  # -----------------------------------------
  # API FastAPI
  # -----------------------------------------
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ../models:/app/models
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped

  # -----------------------------------------
  # MLflow
  # -----------------------------------------
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.10.0
    ports:
      - "5000:5000"
    volumes:
      - ../mlruns:/mlruns
    command: mlflow ui --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:////mlruns/mlflow.db
    restart: unless-stopped

  # -----------------------------------------
  # Airflow - Init (runs once then exits)
  # -----------------------------------------
  airflow-init:
    <<: *airflow-common
    command: bash -c "airflow db migrate && airflow users create --username kawme --password kawme178 --firstname Kaoutar --lastname Mez --role Admin --email kmezouahi@gmail.com"
    restart: "no"

  # -----------------------------------------
  # Airflow - Webserver
  # -----------------------------------------
  airflow-webserver:
    <<: *airflow-common
    ports:
      - "8080:8080"
    command: airflow webserver
    restart: unless-stopped

  # -----------------------------------------
  # Airflow - Scheduler
  # -----------------------------------------
  airflow-scheduler:
    <<: *airflow-common
    command: airflow scheduler
    restart: unless-stopped